### ISSUE TITLE
取消各接口扩展规则中对前缀的强制性要求

### ISSUE THREAD

**Issue by richardchien** [botuniverse/onebot#132]
- 状态：接收 
- 相关 PR：#157 

## 摘要

在事件、动作、消息段的扩展规则中，取消对 `<platform>.` 或 `<impl>.` 前缀的强制性要求。

相关链接：

- [specs/interface/index.md#扩展](https://github.com/botuniverse/onebot/blob/e89e06d817/specs/interface/index.md#%E6%89%A9%E5%B1%95)
- [specs/interface/event/extended.md](https://github.com/botuniverse/onebot/blob/e89e06d817/specs/interface/event/extended.md)
- [specs/interface/action/extended.md](https://github.com/botuniverse/onebot/blob/e89e06d817/specs/interface/action/extended.md)
- [specs/interface/segment/extended.md](https://github.com/botuniverse/onebot/blob/e89e06d817/specs/interface/segment/extended.md)

## 动机

此前强制要求所有扩展的名字都需要加聊天平台或 OneBot 实现专属的前缀，以防止不同平台、不同实现之间发生命名冲突的情况，但实际上这造成了 OneBot 实现的编写不便、用户使用也不便。

目前看来，相比潜在的不同平台、不同实现之前同一个命名含义不同的冲突，OneBot 实现的编写和使用的便捷性更为重要，在标准层面进行强制的前缀约束可能弊大于利。

## 具体描述

本 RFC 提议删掉标准中对**扩展规则**的描述中，强制要求**前缀**的部分，改为**建议**使用前缀但不强制。也就是说，OneBot 实现者可以根据接口的实际情况，包括是不是潜在地适用于不同平台、是否加了前缀会不够直观等因素，来决定要不要加前缀。

相关页面中 JSON 形式的事件、动作、消息段的实例不需要调整，以体现对使用前缀的**建议**。

对前缀的格式要求不变，如果实现决定添加前缀，仍然应该使用 `<impl>.` 或 `<platform>.`。

## 局限

取消了强制前缀约束后，不同平台、实现可能会发生同一个名字的事件、动作、消息段、字段，具有不同的数据类型或含义的情况。但并不意味着我们任由命名冲突发生，而是应由人们根据情况进行冲突避免和解决。具体来说，解决命名冲突有很多办法：

1. 在命名之前进行沟通，需要时提前标准化
2. 发生冲突后沟通，需要时进行标准化，各实现修改为标准含义
3. 发生冲突后在使用时（SDK 或用户代码中）根据 `impl` 和 `platform` 辨别含义

## 替代方案

一个替代方案是在 LibOneBot 和 OneBotSDK 中为前缀提供更为便捷的写法，但这种方案仍然会为 OneBot 实现的编写者和用户带来心智负担，举例来说，人们仍然需要区分：

```python
# OneBot 实现
ob.add_action("send_message", ...)  # 实现 send_message 动作
ob.add_extended_action("get_something", ...)  # 实现 tg.get_something 动作

# OneBot 用户
ob.send_message(...)  # 调用 send_message 动作
ob.tg.send_message(...)  # 调用 tg.get_something 动作
```

实际上，LibOneBot 和 OneBotSDK 仍然可以提供这样的区分方式，这和解除强制性前缀约束不冲突。

**Comment by crazywhalecc** [comment]
去掉的好处就是 API 更开放，但代价就是 OneBot 标准必须更加强有力，因为一旦标准内规定的动作不采用标准实现，那就不能称之为 OneBot 标准的实现。

保留的好处是将标准更加具体到应用上面了，代价就是需要社区之间互相促进其小平台间的约定。

**Comment by richardchien** [comment]
> 但代价就是 OneBot 标准必须更加强有力，因为一旦标准内规定的动作不采用标准实现

是的，如果有某两个实现首先采用了冲突的字段名，随后标准采纳了其中一个，实现不改，就会比较麻烦。

但感觉这是个很难取舍的问题。
