### ISSUE TITLE
将 MessagePack 编码方式改为可选

### ISSUE THREAD

**Issue by richardchien** [botuniverse/onebot#148]
- 状态：接收 
- 相关 PR：#152 

## 摘要

将 MessagePack 编码方式改为可选。

相关讨论：

- https://github.com/botuniverse/onebot/discussions/129

## 动机

MessagePack 编码方式是跟随 `upload_file` 动作引入的，为了减少 base64 编码文件内容的计算和传输开销，但现在发现两个问题：

- 同时支持 MessagePack 和 JSON 对某些语言的 OneBot 实现（和 LibOneBot）来说可能不太简单
- 实现可能并不打算实现 `upload_file` 等文件相关动作，而其它动作没有必要使用 MessagePack 编码方式

## 具体描述

将标准中“OneBotRPC - 通信方式”部分的 MessagePack 编码方式定义为可选支持。

具体来说，

- 对于 HTTP 通信方式，`Content-Type` 为 `application/msgpack` 时可以返回 `415 Unsupported Media Type`
- 对于 HTTP Webhook 通信方式，`Content-Type` 为 `application/msgpack` 时可以输出表示不支持的错误日志
- 对于正向 WebSocket 和反向 WebSocket 通信方式，收到 binary 类型的 WebSocket 消息时，以 JSON 和 UTF-8 编码返回 `10001 Bad Request` 返回码

OneBot SDK 或 OneBot 应用可以通过使用 MessagePack 编码请求 `get_status` 动作来探测 OneBot 实现是否支持 MessagePack。

## 局限

无。

## 替代方案

无。

**Comment by crazywhalecc** [comment]
这个同意，我认为没什么大问题，毕竟有些平台可能并不需要上传下载文件。
