### ISSUE TITLE
添加两级群组 (Guild-Channel) 支持

### ISSUE THREAD

**Issue by abrahum** [botuniverse/onebot#154]
- 状态：候选 
- 相关 PR：#160

## 摘要

添加对于频道的支持

相关链接： [关于频道（Guild）相关事件以及 API #131](https://github.com/botuniverse/onebot/discussions/131)

## 动机

目前协议内仅存在单用户接口与单级群组接口，对于频道以及类似的两级群组缺乏必要的支持。

本 RFC 提议向现有协议增加两级群组相关接口，以扩大 OneBot 协议的适用范围。

## 具体描述

两级群组需要增加以下接口

#### message.channel 频道消息

字段名 | 数据类型 | 说明
-- | -- | -- 
detail_type | string | 必须为 channel
message_id | string | 消息唯一 ID
message | message | 消息内容
alt_message | string | 消息内容的替代表示, 可以为空
guild_id | string | 群组 ID
channel_id | string | 频道 ID
user_id | string | 用户 ID

#### notice.guild_member_increase 群组成员增加

字段名 | 数据类型 | 说明
-- | -- | --
detail_type | string | 必须为 guild_member_increase
sub_type | string | 必须为 join、invite、空字符串或扩展的子类型
guild_id| string | 群组 ID
user_id | string | 用户 ID
operator_id | string | 操作者 ID

#### notice.guild_member_decrease 群组成员减少

字段名 | 数据类型 | 说明
-- | -- | --
detail_type | string | 必须为 guild_member_decrease
sub_type | string | 必须为 leave、kick、空字符串或扩展的子类型
guild_id | string | 群组 ID
user_id | string | 用户 ID
operator_id | string | 操作者 ID

#### notice.channel_message_delete 频道消息删除

字段名 | 数据类型 | 说明
-- | -- | --
detail_type | string | 必须为 channel_message_delete
sub_type | string | 必须为 recall、delete、空字符串或扩展的子类型
guild_id | string | 群组 ID
channel_id | string | 频道 ID
message_id | string | 消息 ID
user_id | string | 消息发送者 ID
operator_id | string | 操作者 ID

#### notice.channel_create 新建频道

字段名 | 数据类型 | 说明
-- | -- | --
detail_type | string | 必须为 channel_create
guild_id | string | 群组 ID
channel_id | string | 频道 ID
operator_id | string | 操作者 ID

#### notice.channel_delete 删除频道

字段名 | 数据类型 | 说明
-- | -- | --
detail_type | string | 必须为 channel_delete 
guild_id | string | 群组 ID
channel_id | string | 频道 ID
operator_id | string | 操作者 ID

### 动作

消息动作 send_message 发送消息需要增加 detail_type: "channel"，以及 guild_id 和 channel_id 字段

#### get_guild_info 获取群组信息

请求参数

字段名 | 数据类型 | 默认值 | 说明
-- | -- | -- | --
guild_id | string | - | 群组 ID

响应数据

字段名 | 数据类型 | 默认值 | 说明
-- | -- | -- | --
guild_id | string | - | 群组 ID
guild_name | string | - | 群组名称

#### get_guild_list 获取群组列表

无请求参数，响应数据参见 get_guild_info 

#### get_channel_info 获取频道信息

请求参数

字段名 | 数据类型 | 默认值 | 说明
-- | -- | -- | --
guild_id | string | - | 群组 ID
channel_id | string | - | 频道 ID

响应数据

字段名 | 数据类型 | 默认值 | 说明
-- | -- | -- | --
channel_id | string | - | 频道 ID
channel_name | string | - | 频道名称

#### get_channel_list 获取频道列表

请求参数

字段名 | 数据类型 | 默认值 | 说明
-- | -- | -- | --
guild_id | string | - | 群组 ID

响应数据参见 get_channel_info 

#### get_guild_member_info 获取群组成员信息

请求参数

字段名 | 数据类型 | 默认值 | 说明
-- | -- | -- | --
guild_id| string | - | 群组 ID
user_id | string | - | 用户 ID

响应数据

字段名 | 数据类型 | 默认值 | 说明
-- | -- | -- | --
user_id | string | - | 用户 ID
nickname | string | - | 用户名称/昵称

#### get_guild_member_list 获取群组成员列表

字段名 | 数据类型 | 默认值 | 说明
-- | -- | -- | --
guild_id| string | - | 群组 ID

响应数据参见 get_guild_member_info 

#### set_guild_name 设置群组名称

字段名 | 数据类型 | 默认值 | 说明
-- | -- | -- | --
guild_id | string | - | 群组 ID
guild_name | string | - | 新群组名称

无响应数据

#### set_channel_name 设置频道名称

字段名 | 数据类型 | 默认值 | 说明
-- | -- | -- | --
guild_id | string | - | 群组 ID
channel_id | string | - | 频道 ID
channel_name | string | - | 新频道名称

无响应数据

#### leave_guild 退出群组

字段名 | 数据类型 | 默认值 | 说明
-- | -- | -- | --
guild_id| string | - | 群组 ID

无响应数据

## 局限

- 目前两级群组没有可参考的成熟用例
- 各 IM Guild API 未完全确定，本 RFC 所建议增加的接口是参考目前各家 API 选取尽可能的交集提出
- 对于 Role 等未提供很好的支持，需要后续其他 RFC 继续完善。

## 替代方案

可以将两级群组减并为单级群组接口的扩展实现:

使用单级群组增加 guild.id 的形式代替 guild_id， 原 group_id 记录 channel_id。

但是该方案缺少直接的 Guild 相关接口，亦无法体现 Guild-Channel 的从属关系。

**Comment by richardchien** [comment]
`guild_user` 改成 `guild_member` 怎么样，可以和 group 保持一致
