### ISSUE TITLE
正向 WebSocket 支持使用 `Sec-WebSocket-Protocol` 头传递鉴权 token

### ISSUE THREAD

**Issue by idanran** [botuniverse/onebot#164]
- 状态：关闭 
- 相关 PR：无 

## 摘要

修改原有鉴权方式。

## 动机

在浏览器端发起 WebSocket 连接时无法操作 Header。

## 具体描述

`var aWebSocket = new WebSocket(url [, protocols]);`
以上为 WebSocket 标准语法，参见 [MDN](https://developer.mozilla.org/zh-CN/docs/Web/API/WebSocket/WebSocket)。
建议通过 protocols 参数（Sec-WebSocket-Protocol 头）传输 access_token。

### 鉴权

如果配置了 access_token 且不为空字符串，OneBot 实现必须在连接建立前（协议 upgrade 前）检查请求头中的 Sec-WebSocket-Protocol 头是否等于 <access_token>（<access_token> 不需要对两边的空白字符进行裁剪），若等于则认为鉴权成功，否则鉴权失败。

## 局限

这并不是 protocols 参数应该做的事。

## 替代方案

可以在 WebSocket 消息中包含 access_token 字段。

**Comment by abrahum** [comment]
增加一个鉴权元事件感觉比在每个事件增加字段成本更低，但是依然不能和现有header鉴权兼容。

**Comment by idanran** [comment]
> 增加一个鉴权元事件感觉比在每个事件增加字段成本更低，但是依然不能和现有header鉴权兼容。

关于具体实现，我的猜想是：让 WS 客户端向 WS 服务端发送 access_token，不匹配则断开连接。感觉可能会有一些意料之外的事情发生，比如在鉴权未完成之前进行其它操作。

**Comment by idanran** [comment]
> > 增加一个鉴权元事件感觉比在每个事件增加字段成本更低，但是依然不能和现有header鉴权兼容。
> 
> 关于具体实现，我的猜想是：让 WS 客户端向 WS 服务端发送带有 access_token 的鉴权元事件，不匹配则断开连接。感觉可能会有一些意料之外的事情发生，比如在鉴权未完成时进行其它操作。

**Comment by richardchien** [comment]
最简单的其实是允许 url 里面加上 query 参数：`/?access_token=xxx`，以前 CQHTTP 是这样做的

**Comment by idanran** [comment]
> 最简单的其实是允许 url 里面加上 query 参数：`/?access_token=xxx`，以前 CQHTTP 是这样做的

看起来确实挺简单的

**Comment by A-kirami** [comment]
是否可参考 socket.io 的鉴权实现？在 socket.io 中，有 auth 这一配置
[socket.io-auth](https://socket.io/docs/v4/client-options/#auth)

**Comment by idanran** [comment]
> 是否可参考 socket.io 的鉴权实现？在 socket.io 中，有 auth 这一配置
> [socket.io-auth](https://socket.io/docs/v4/client-options/#auth)

感觉不可行，从浏览器的原生 API 来看，是做不到修改 header 的。

**Comment by A-kirami** [comment]
> > 是否可参考 socket.io 的鉴权实现？在 socket.io 中，有 auth 这一配置
> > [socket.io-auth](https://socket.io/docs/v4/client-options/#auth)
> 
> 感觉不可行，从浏览器的原生 API 来看，是做不到修改 header 的。

socket.io 的鉴权不是修改 header，应该是额外发送一次验证
![image](https://user-images.githubusercontent.com/66513481/165425088-71ddef1c-d1e8-40ba-8642-1c3c52bbae33.png)

**Comment by idanran** [comment]
> > > 是否可参考 socket.io 的鉴权实现？在 socket.io 中，有 auth 这一配置
> > > [socket.io-auth](https://socket.io/docs/v4/client-options/#auth)
> > 
> > 
> > 感觉不可行，从浏览器的原生 API 来看，是做不到修改 header 的。
> 
> socket.io 的鉴权不是修改 header，应该是额外发送一次验证 ![image](https://user-images.githubusercontent.com/66513481/165425088-71ddef1c-d1e8-40ba-8642-1c3c52bbae33.png)

额...看起来跟上面那个鉴权元事件差不多
