### ISSUE TITLE
增加用于定时任务的元事件

### ISSUE THREAD

**Issue by idanran** [botuniverse/onebot#165]
- 状态：关闭 
- 相关 PR：无 

## 摘要

可以使得在每一天的某个时刻，向 OneBot 应用端派发指定任务。

## 动机

让 OneBot 实现端定时派发任务成为可能。

### 事件字段

| 字段名 | 数据类型 | 说明 |
| ------- | ------- | ------- |
| task | string | 任务名称 |

可以要求 OneBot 实现端不一定实现此事件

**Comment by richardchien** [comment]
感觉这个需求在应用端自行实现比较合理
