### ISSUE TITLE
明确事件 `time` 字段表述

### ISSUE THREAD

**Issue by richardchien** [botuniverse/onebot#176]
- 状态：接收 
- 相关 PR：#184 

## 摘要

明确事件的基本字段 `time` 的含义为事件在 IM 平台上的发生时间，如果无法得知平台发生时间，才应使用 OneBot 实现中的事件对象产生时间。

## 动机

根据 #170 的讨论发现此处表述有模糊。

## 具体描述

修改“OneBotRPC - 数据协议 - 事件”页面的 `time` 字段说明为“事件发生时间（Unix 时间戳），单位：秒，建议优先采用聊天平台给出的时间，其次采用实现中创建事件对象的时间”。

## 局限

无。

## 替代方案

无。

**Comment by crazywhalecc** [comment]
感觉没得问题。
