### ISSUE TITLE
明确 `get_latest_events` 的行为

### ISSUE THREAD

**Issue by crazywhalecc** [botuniverse/onebot#182]
## 摘要

明确 `get_latest_events` 动作在不同通信方式下的响应方式以及规定部分未定义行为。

## 动机

这个问题是编写 LibOB 时发现的，当 OneBot 产生一个事件时，在开发层面发现 OneBot 12 当前的标准文档中未定义一些边缘行为。

### OneBot Connect - 通信方式 - HTTP - 事件轮询

补充描述：

> 不同通信方式之间应该相互隔离，即，无论其它通信方式上是否成功推送事件，`get_latest_events` 都应该能收到所有事件（在未超出缓冲区的情况下）。OneBot 实现应建议用户不要同时使用 `get_latest_events` 和其它通信方式来接收事件。

修改描述：

> 多个并发请求同时调用 `get_latest_events` 是未定义行为，OneBot 实现可以做任意假设。

为：

> 多个并发请求同时调用 `get_latest_events` 的结果由 OneBot 实现定义，实现可以对后来的请求返回错误码、返回空事件列表或是对所有请求返回相同的事件列表。

### 接口定义 - 元接口 - 元动作 - `get_latest_events`

修改 `timeout` 参数说明为：

> 没有事件时最多等待的秒数，0 表示使用短轮询，不等待

## 局限

无

## 替代方案

无

**Comment by richardchien** [comment]
> 当存在其他通信方式时，假设此动作允许在其他动作下调用，应该返回什么事件？
> 
> 在上一条的前提下，在其他通信方式对一个事件已进行过处理后，例如消息事件已通过调用回复消息动作进行回复，这时如果调用此动作时，是否应该返回被回复的事件？

如果以不同通信方式是相互隔离的假设为前提，这里就是其他通信方式的接收与否、回复与否，都不影响 `get_latest_events`，我觉得这里可以理解为，这种通信方式不会和其他的通信方式同时使用（比如正向 WS 和反向 WS 也会重复收事件），所以不会有重复收事件的问题，如果用户同时用了这些通信方式，那是 ta 代码写的有问题。

如果这个假设如果能够获得一致的认可的话，可以加到标准里，防止实现出现不一样的行为。



> 当在 HTTP 通信方式下调用时，获取返回的事件理论上应该从队列或缓存等数据结构中删除，此时如果事件队列或缓存为空，`timeout` 字段如果不为 0 的时候，是在收到新的事件后立刻返回包含一个事件的结果，还是直到 `timeout` 的值，返回这阶段内收到的所有事件？

收到立刻返回，因为 `timeout` 是“等待有事件来”的 timeout，不是“等待拿满 `limit` 个事件”的 timeout。
